### ISSUE TITLE
Error while doing npm install

### ISSUE THREAD

**Issue by jrmi** [mabhub/puppeteer-screenshot-cli#3]
when I am doing a npm install I got this error :
```bash
npm install -g puppeteer-screenshot-cli
/home/xxx/.nvm/versions/node/v5.12.0/bin/puppeteer-screenshot -> /home/xxx/.nvm/versions/node/v5.12.0/lib/node_modules/puppeteer-screenshot-cli/index.js

> puppeteer@1.0.0 install /home/xxx/.nvm/versions/node/v5.12.0/lib/node_modules/puppeteer-screenshot-cli/node_modules/puppeteer
> node install.js

/home/xxx/.nvm/versions/node/v5.12.0/lib/node_modules/puppeteer-screenshot-cli/node_modules/puppeteer/install.js:66
  const cleanupOldVersions = allRevisions.map(({platform, revision}) => downloader.removeRevision(platform, revision));
                                               ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
/home/xxx/.nvm/versions/node/v5.12.0/lib
└── (empty)

npm ERR! Linux 4.13.0-32-generic
npm ERR! argv "/home/xxx/.nvm/versions/node/v5.12.0/bin/node" "/home/xxx/.nvm/versions/node/v5.12.0/bin/npm" "install" "-g" "puppeteer-screenshot-cli"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! puppeteer@1.0.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.0.0 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the puppeteer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs puppeteer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls puppeteer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xxx/Code/tereval/npm-debug.log
npm ERR! code 1
```

**Comment by mabhub** [comment]
Looks like you tried to install it with node `5.12.0`, but Puppeteer itself can't be installed with a version lower than `6.4.0`.

I've add `engines` requirement to `package.json` to avoid later confusion.

Thanks for your report !
